import { describe, expect, it } from "vitest";
import {
  defaultModelFor,
  providerKeyEnv,
  renderProfileManifest,
  renderProfilePatch,
  renderProfileRoot,
} from "./profile.ts";

describe("renderProfileManifest", () => {
  it("names both bundle layers in application order", () => {
    const manifest = JSON.parse(renderProfileManifest()) as {
      dsh: { profile: { bundles: string[]; patchReload: string } };
    };
    expect(manifest.dsh.profile.bundles).toEqual([
      "@deepseek-ai/dsh-base",
      "@deepseek-ai/dsh-acp-app",
    ]);
  });

  it("asks for startup patch reload, not live", () => {
    // Live reload installs file watchers and an HMR plugin so a patch edit recomposes the tree. This
    // patch is generated by Electron and changes only when Electron restarts the child, so a watcher
    // would only add a way for the tree to change underneath a running turn.
    const manifest = JSON.parse(renderProfileManifest()) as {
      dsh: { profile: { patchReload: string } };
    };
    expect(manifest.dsh.profile.patchReload).toBe("startup");
  });
});

describe("renderProfileRoot", () => {
  it("is an empty entry list, because every row arrives as a patch", () => {
    expect(renderProfileRoot().trimEnd().endsWith("[]")).toBe(true);
  });
});

describe("renderProfilePatch", () => {
  const patch = (providers: ("openai" | "anthropic")[]) =>
    renderProfilePatch({ providers, defaultProvider: providers[0] ?? null, defaultModel: null });

  it("disables telemetry export", () => {
    // dsh-base mounts session-telemetry-otel at FEEDBACK_ONLY against a DeepSeek endpoint, and a row
    // can only be switched off by a patch. If this assertion ever fails, a privacy-forward product
    // has started exporting.
    expect(patch(["openai"])).toContain("- id: session-telemetry-otel\n  disabled: true");
  });

  it("disables the DeepSeek web rows, whose key this product never asks for", () => {
    const rendered = patch(["openai"]);
    expect(rendered).toContain("- id: web-search-deepseek\n  disabled: true");
    expect(rendered).toContain("- id: tool-web\n  disabled: true");
  });

  it("disables dsh-base's own DeepSeek route", () => {
    // Verified against a running harness: left mounted, `llm-deepseek` puts a whole DeepSeek group in
    // the ACP model picker for an account that has no DeepSeek key, and every model in it can only
    // 401. Disabled, the catalog comes back holding exactly the routes this patch configured.
    expect(patch(["openai"])).toContain("- id: llm-deepseek\n  disabled: true");
  });

  it("emits only the routes whose key exists", () => {
    const rendered = patch(["anthropic"]);
    expect(rendered).toContain(`        apiKeyEnv: ${providerKeyEnv.anthropic}`);
    expect(rendered).not.toContain(providerKeyEnv.openai);
  });

  it("emits a route per key when the device holds both", () => {
    const rendered = patch(["openai", "anthropic"]);
    expect(rendered).toContain(`        apiKeyEnv: ${providerKeyEnv.openai}`);
    expect(rendered).toContain(`        apiKeyEnv: ${providerKeyEnv.anthropic}`);
  });

  it("contains no key material, only variable names", () => {
    const rendered = renderProfilePatch({
      providers: ["openai"],
      defaultProvider: "openai",
      defaultModel: "gpt-5.2",
    });
    // The whole point of `apiKeyEnv`: the reference is resolved per request from the launch
    // environment, so a secret has no reason to be in any file dsh reads.
    expect(rendered).not.toMatch(/sk-/);
    expect(rendered).not.toMatch(/\bkey:\s*\S/);
  });

  it("restates the acp row in full rather than leaving dsh's DeepSeek default in place", () => {
    // A patch replaces the targeted row's whole config; a row left untouched keeps
    // `provider: deepseek-official`, which would advertise a route this product never configures.
    const rendered = patch(["openai"]);
    expect(rendered).toContain("- id: acp\n  config:\n    provider: openai");
    expect(rendered).not.toContain("deepseek-official");
  });

  it("defaults the route to one whose key exists, even when the preference names another", () => {
    // The first turn of a fresh conversation happens before any picker is touched, so the default has
    // to be servable rather than merely remembered.
    const rendered = renderProfilePatch({
      providers: ["anthropic"],
      defaultProvider: "openai",
      defaultModel: "gpt-5.2",
    });
    expect(rendered).toContain("provider: anthropic");
    expect(rendered).toContain(`model: ${JSON.stringify(defaultModelFor("anthropic"))}`);
  });

  it("emits an empty route set and a null default when the device holds no key", () => {
    const rendered = renderProfilePatch({
      providers: [],
      defaultProvider: null,
      defaultModel: null,
    });
    expect(rendered).toContain("providers: {}");
    expect(rendered).toContain("provider: null");
  });

  it("quotes the model id, so a value with YAML meaning cannot reshape the document", () => {
    const rendered = renderProfilePatch({
      providers: ["openai"],
      defaultProvider: "openai",
      defaultModel: "yes: no",
    });
    expect(rendered).toContain('model: "yes: no"');
  });
});
