/**
 * The Electron-owned dsh profile, rendered as text.
 *
 * dsh composes a profile from patch layers: each bundle in `dsh.profile.bundles` order, then the
 * profile's own `cordis.patch.yml`. Those three files are the whole of Symplist's policy over a
 * ~230-plugin tree, and this module renders them so the rendering is testable — the writer beside it
 * only puts the strings on disk.
 *
 * Four properties are load-bearing, and each one is something dsh decided:
 *
 * **The profile lives in `userData`, not in the app bundle.** dsh rewrites `cordis.yml` on every
 * launch, deliberately: the Loader's tree write-back can bake composed rows into it, and a stale
 * copy would duplicate every bundle insert on the next boot. A profile inside a read-only
 * `Resources` directory therefore either fails with `EROFS` or silently corrupts itself.
 *
 * **The profile name is `desktop`.** `dsh/lib/bin.js` refuses it — *profile "desktop" is managed
 * exclusively by the Electron application* — which is exactly the guarantee wanted: nothing a user
 * types at a shell can reach, edit or boot this profile.
 *
 * **A patch replaces a row's whole `config`; it does not merge into it.** So every row this patch
 * touches is restated in full, including the fields being kept.
 *
 * **Only routes whose key is actually present are emitted.** The ACP model catalog is built from the
 * routes that exist, so advertising a provider with no key would offer the user a model that can
 * only 401. With no key at all there is no route, and the supervisor does not spawn a child.
 *
 * Nothing here contains a secret. `apiKeyEnv` is a *reference*: `dsh-credentials-local` resolves it
 * per request against the launch environment, whose precedence is launch environment > stored file >
 * project `.env` > home `.env`, and whose launch layer is explicitly read-only. So the key reaches
 * the process that calls the provider and nothing in dsh can persist or overwrite it.
 */

/** The provider routes Symplist supports. OpenAI and Anthropic only, as the cloud settled. */
export type AssistantProvider = "openai" | "anthropic";

/** The environment variable each route's key travels in, and the only form of it in any file. */
export const providerKeyEnv: Readonly<Record<AssistantProvider, string>> = Object.freeze({
  openai: "SYMPLIST_OPENAI_API_KEY",
  anthropic: "SYMPLIST_ANTHROPIC_API_KEY",
});

/** The bundle layers the ACP profile composes, in application order. */
const PROFILE_BUNDLES = ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-acp-app"] as const;

/**
 * Rows disabled outright, with the reason each one cannot simply be configured away.
 *
 * `session-telemetry-otel` is the important one: `dsh-base` mounts it defaulting to
 * `FEEDBACK_ONLY` against a DeepSeek endpoint, carrying an anonymous id from
 * `$DSH_HOME/.anonymous-user-id`. Config cannot switch a row off — only a patch can — so if this
 * list ever loses the row, a privacy-forward product starts exporting. `DSH_TELEMETRY_DISABLED` is
 * also set on the child, but that is a belt: it only produces a patch when the row is present, and
 * relying on an environment variable for a privacy default is the wrong way round.
 *
 * The two web rows resolve `DEEPSEEK_API_KEY`, which no Symplist account has and which the product
 * never asks for, so mounted they can only fail at the moment the agent tries to search.
 */
const DISABLED_ROWS: readonly { readonly id: string; readonly why: string }[] = Object.freeze([
  {
    id: "session-telemetry-otel",
    why: "dsh-base mounts OpenTelemetry export to a DeepSeek endpoint by default; a row can only be switched off by a patch.",
  },
  {
    id: "web-search-deepseek",
    why: "resolves DEEPSEEK_API_KEY, which this product never asks for.",
  },
  { id: "tool-web", why: "its search half depends on the disabled DeepSeek route." },
  {
    id: "llm-deepseek",
    why: "dsh-base's native DeepSeek adapter registers its route unconditionally, so its whole model catalog appears in the ACP picker for an account that has no DeepSeek key and never will — every one of those models can only 401.",
  },
]);

/** The profile's `package.json`: the bundle list and the patch lifecycle, nothing else. */
export function renderProfileManifest(): string {
  const manifest = {
    name: "symplist-desktop-profile",
    private: true,
    version: "0.0.0",
    // Generated fresh on every launch, so nothing is installed into it and it declares nothing.
    // Plugin specifiers resolve through the module fallback the launcher heals into `$DSH_HOME`.
    dependencies: {},
    dsh: {
      profile: {
        bundles: [...PROFILE_BUNDLES],
        // `startup`, not `live`: live reload installs file watchers and an HMR plugin to recompose
        // the tree on a patch edit. The patch is generated by this process and changes only when
        // Electron restarts the child, so a watcher would only add a way for the tree to change
        // underneath a running turn.
        patchReload: "startup",
      },
    },
  };
  return `${JSON.stringify(manifest, undefined, 2)}\n`;
}

/**
 * The root config: an empty entry list. It exists on disk only because the Loader needs a real
 * include root to anchor `baseUrl` on; every row comes from a patch layer.
 */
export function renderProfileRoot(): string {
  return `# Symplist's dsh profile root — an empty entry list, rewritten by Electron on every launch.
# The tree is composed entirely as patches: each bundle in package.json's dsh.profile.bundles, then
# cordis.patch.yml. Both of those files are generated too; editing either one by hand is pointless.
[]
`;
}

export interface ProfilePatchInput {
  /** The providers whose keys the keychain actually holds. An empty list emits no route. */
  readonly providers: readonly AssistantProvider[];
  /** The route a new session starts on. Must be one of `providers`, or it is ignored. */
  readonly defaultProvider: AssistantProvider | null;
  /** The model id on that route, as the provider spells it. Not validated against any allowlist. */
  readonly defaultModel: string | null;
}

/**
 * The user patch layer: the routes, the default the `acp` row hands every new session, and the rows
 * that must not run.
 *
 * YAML is written by hand rather than through a serializer because every line here is a decision
 * that deserves the comment beside it, and because the file has exactly one writer. Values that
 * reach it are either fixed strings from this module or a model id, which is quoted.
 */
export function renderProfilePatch(input: ProfilePatchInput): string {
  const lines: string[] = [
    "# Symplist's patch layer over dsh-base + dsh-acp-app. GENERATED on every launch by",
    "# apps/desktop/src/main/harness/profile.ts — edits are overwritten.",
    "#",
    "# A patch replaces a row's whole `config` rather than merging into it, so each row below",
    "# restates every field it wants, including the ones it is keeping.",
    "",
  ];

  for (const row of DISABLED_ROWS) {
    lines.push(`# ${row.why}`, `- id: ${row.id}`, "  disabled: true", "");
  }

  lines.push(
    "# The pi-ai multi-provider adapter, mounted dormant by dsh-base with zero routes. These routes",
    "# are what make models appear in the ACP catalog at all. `apiKeyEnv` is a reference resolved per",
    "# request from the launch environment — no key is in this file, and the launch layer is read-only",
    "# to the harness, so nothing can persist one to $DSH_HOME/.credentials.yaml.",
    "- id: llm-pi-ai",
    "  config:",
  );
  if (input.providers.length === 0) {
    // A route set of `{}` is the dormant state dsh-base ships, restated so the row's config is
    // complete. The supervisor does not spawn a child in this state; the patch stays truthful anyway.
    lines.push("    providers: {}");
  } else {
    lines.push("    providers:");
    for (const provider of input.providers) {
      lines.push(`      ${provider}:`, `        apiKeyEnv: ${providerKeyEnv[provider]}`);
    }
  }
  lines.push("");

  // A model id belongs to a route, so a fallback to another route must drop it: pairing the
  // preference's model with a different provider's route produces a configuration that looks
  // deliberate and fails with UNKNOWN_MODEL on the first turn.
  const preferred =
    input.defaultProvider !== null && input.providers.includes(input.defaultProvider)
      ? input.defaultProvider
      : null;
  const provider = preferred ?? input.providers[0] ?? null;
  const model = preferred !== null ? (input.defaultModel ?? defaultModelFor(preferred)) : null;
  lines.push(
    "# Every session this server creates starts on this route. A client may change it per session",
    "# with session/set_config_option, but the default has to be a route whose key exists — the first",
    "# turn of a fresh conversation happens before any picker is touched.",
    "- id: acp",
    "  config:",
  );
  if (provider === null) {
    // Restated empty rather than omitted: leaving the row's shipped `deepseek-official` default in
    // place would advertise a route this product never configures.
    lines.push("    provider: null", "    model: null");
  } else {
    lines.push(`    provider: ${provider}`);
    lines.push(`    model: ${JSON.stringify(model ?? defaultModelFor(provider))}`);
  }

  return `${lines.join("\n")}\n`;
}

/**
 * The model a route falls back to when the account has chosen none. A convenience, not an allowlist:
 * a typed id is accepted everywhere, so a model newer than this file works without a release.
 */
export function defaultModelFor(provider: AssistantProvider): string {
  return provider === "openai" ? "gpt-5.2" : "claude-sonnet-4-5";
}
