import { timingSafeEqual } from "node:crypto";
import { Controller, HttpCode, Inject, Post, Req, Res } from "@nestjs/common";
import type { MeResponse } from "@symplist/contracts";
import type { LocalOwnerService, ProfileService } from "@symplist/core/access";
import type { Request, Response } from "express";
import { SessionService } from "../../common/auth/session.service.ts";
import { CLOCK, type Clock } from "../../common/clock.ts";
import { ApiError } from "../../common/errors/api-error.ts";
import { AppLogger } from "../../common/logging/logger.ts";
import { RouteClass } from "../../common/route-classes.ts";
import { API_CONFIG, type ApiConfig } from "../../infra/config/api-config.ts";
import { LOCAL_OWNER_SERVICE, PROFILE_SERVICE } from "./access.tokens.ts";

/** The header the desktop app presents. Not `Authorization`: this is not a bearer for any principal. */
export const LOCAL_OWNER_HEADER = "x-symplist-local";

/**
 * Sign-in for a local install (`DEPLOYMENT=local`, note 18).
 *
 * A local deployment is one person's own machine with nothing behind it: no email for an OTP, no invite
 * to redeem, no administrator. So there is one owner, and this is how the app that started the api gets
 * a session for it.
 *
 * **It is not an authentication bypass.** The owner is an ordinary `users` row and what comes back is an
 * ordinary session from the ordinary `SessionStore`, subject to every guard, every `evaluateAccess` call
 * and every owner-scoped query exactly as a cloud session is. Nothing downstream knows this route
 * exists. That matters more than the convenience: a local-mode branch inside a guard would be a cloud
 * vulnerability one configuration mistake away, and there is none.
 *
 * **What authorizes it is a per-launch secret, because a loopback port is not a boundary.** Every other
 * process on the machine can reach `127.0.0.1:<port>`, and this route hands out the owner's session —
 * so "it is only listening locally" is not an argument, it is the threat. `LOCAL_OWNER_TOKEN` is
 * generated by the app, passed to the api it spawns in that child's environment, never written down and
 * never the same twice. A process that can already read another process's environment has the session
 * anyway; one that cannot, cannot guess this.
 *
 * **In a cloud deployment it cannot work, for two independent reasons.** The handler answers 404 unless
 * `DEPLOYMENT=local`, so the route is indistinguishable from one that was never registered — and the
 * `LocalOwnerService` it would need is bound to null there, so even a mistake in that check has nothing
 * to provision an owner with. Nest registers controllers statically, so "not mounted at all" is not
 * available without making the whole access module dynamic; two barriers that each fail closed is the
 * honest version of the same guarantee.
 */
@Controller("auth")
export class LocalOwnerController {
  constructor(
    @Inject(LOCAL_OWNER_SERVICE) private readonly owner: LocalOwnerService | null,
    @Inject(PROFILE_SERVICE) private readonly profile: ProfileService,
    @Inject(API_CONFIG) private readonly config: ApiConfig,
    @Inject(CLOCK) private readonly clock: Clock,
    private readonly sessions: SessionService,
    private readonly logger: AppLogger,
  ) {}

  /**
   * Provisions the owner if this is the first boot and returns a session for it.
   *
   * Idempotent in both halves: the row is created once by unique address, and a second call simply
   * mints a second session — which is correct, because the app calls this on every launch and an old
   * session it no longer holds should expire on its own rather than be reused.
   */
  @Post("local")
  @RouteClass("local_owner")
  @HttpCode(200)
  async signIn(
    @Req() req: Request,
    @Res({ passthrough: true }) res: Response,
  ): Promise<MeResponse> {
    /*
     * Not a local deployment: answer exactly as an unregistered route would. A 401 here would tell a
     * caller the route exists, and a cloud deployment should not admit even that.
     */
    if (this.config.DEPLOYMENT !== "local" || this.owner === null) {
      throw new ApiError("not_found");
    }
    const expected = this.config.LOCAL_OWNER_TOKEN;
    if (expected === undefined) {
      // Unreachable: the config refuses to load without it in this deployment. Answered rather than
      // thrown as an internal error, so a misconfiguration reads as a refusal instead of a crash.
      throw new ApiError("auth.session_required");
    }
    if (!matches(req.headers[LOCAL_OWNER_HEADER], expected)) {
      // No detail, and nothing about the expected value's shape or length.
      this.logger.warn("access.local_owner_refused");
      throw new ApiError("auth.session_required");
    }
    const userId = await this.owner.ensure();
    const session = await this.sessions.store.create({ userId, now: this.clock.now() });
    if (!session) throw new ApiError("auth.account_unavailable");
    this.sessions.setCookies(res, session);
    this.logger.info("access.local_owner_signed_in");
    return (await this.profile.me(userId)).me;
  }
}

/**
 * Constant-time comparison of the presented header against the expected token.
 *
 * Length is compared first and separately because `timingSafeEqual` throws on a length mismatch; that
 * leak is the length of a value the caller already chose, not of the secret.
 */
function matches(presented: string | string[] | undefined, expected: string): boolean {
  if (typeof presented !== "string") return false;
  const a = Buffer.from(presented, "utf8");
  const b = Buffer.from(expected, "utf8");
  return a.length === b.length && timingSafeEqual(a, b);
}
