-- Closed beta invites (note 04, architecture §5.4). A code is 160 random bits shown once to the
-- administrator; only its HMAC digest under INVITE_DIGEST_SECRET (with the key version) and a short
-- non-secret hint are stored. The redemption count is derived from beta_redemptions, never stored.
-- Labels are private notes, encrypted under the creating administrator's account key (§4.4). No
-- foreign keys to users: invites outlive the administrators who created or revoked them.
CREATE TABLE beta_invites (
  id TEXT PRIMARY KEY NOT NULL,
  -- Every code generated by one request shares a campaign id (campaign revocation, §5.5).
  campaign_id TEXT NOT NULL,
  -- 'independent': one code per person; 'shared': one campaign code with a larger cap.
  mode TEXT NOT NULL CHECK (mode IN ('independent', 'shared')),
  digest TEXT NOT NULL UNIQUE CHECK (length(digest) = 43),
  digest_version INTEGER NOT NULL CHECK (digest_version >= 1),
  -- The last four Base32 characters of the code.
  hint TEXT NOT NULL CHECK (length(hint) = 4 AND hint NOT GLOB '*[^A-Z2-7]*'),
  label_enc TEXT,
  label_owner_id TEXT,
  -- A normalized address that alone may redeem the code (§4.4 plaintext operational metadata).
  bound_email TEXT CHECK (
    bound_email IS NULL OR (length(bound_email) BETWEEN 3 AND 320 AND instr(bound_email, '@') > 1)
  ),
  max_redemptions INTEGER NOT NULL CHECK (max_redemptions BETWEEN 1 AND 10000),
  expires_at INTEGER NOT NULL,
  created_by TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  revoked_at INTEGER,
  revoked_by TEXT,
  -- Incremented by every administrative edit, so a concurrent edit is refused (expectedVersion).
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  updated_at INTEGER NOT NULL,
  write_id TEXT NOT NULL,
  CHECK (expires_at > created_at),
  CHECK ((label_enc IS NULL) = (label_owner_id IS NULL)),
  CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
) STRICT;

-- The inventory lists newest first with a (created_at, id) cursor.
CREATE INDEX beta_invites_created ON beta_invites (created_at, id);
CREATE INDEX beta_invites_campaign ON beta_invites (campaign_id);
