import { randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { parseEnv } from "node:util";
import {
  apiSecretFamilies,
  apiVariableNames,
  parseApiConfig,
} from "../../packages/config/src/api.ts";
import { liveTestFlagNames } from "../../packages/config/src/live.ts";
import {
  generatedSecretFamilies,
  isSecretVariable,
  providerCredentialInventory,
  secretFamilyInventory,
} from "../../packages/config/src/secrets.ts";
import { parseWebConfig, webVariableNames } from "../../packages/config/src/web.ts";
import {
  parseWorkerConfig,
  workerSecretFamilies,
  workerVariableNames,
} from "../../packages/config/src/worker.ts";

const appTargets = Object.freeze({
  api: Object.freeze({ example: "apps/api/env.example", output: "apps/api/.env" }),
  worker: Object.freeze({ example: "apps/worker/env.example", output: "apps/worker/.env" }),
  web: Object.freeze({ example: "apps/web/env.example", output: "apps/web/.env" }),
});

const privateMode = 0o600;
const permittedSourceOnlyVariables = new Set([
  "CLOUDFLARE_D1_MIGRATE_API_TOKEN",
  "TRIGGER_ACCESS_TOKEN",
  "R2_ACCOUNT_API_TOKEN",
  "LIVE_TRIGGER_TASK_ID",
  ...liveTestFlagNames,
]);

/** A failure safe to show to an operator: it contains variable names, never values. */
export class EnvironmentDistributionError extends Error {
  constructor(message) {
    super(message);
    this.name = "EnvironmentDistributionError";
  }
}

function parseEnvSafe(text, label) {
  try {
    return parseEnv(text);
  } catch {
    throw new EnvironmentDistributionError(`${label} is not valid dotenv syntax`);
  }
}

/** Assignment names in template order. Templates deliberately keep one assignment per line. */
export function assignmentNames(text, label = "environment template") {
  const names = [];
  const seen = new Set();
  for (const match of text.matchAll(/^(?:export[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]*=/gm)) {
    const name = match[1];
    if (seen.has(name)) {
      throw new EnvironmentDistributionError(`${label} assigns ${name} more than once`);
    }
    seen.add(name);
    names.push(name);
  }
  return names;
}

function generatedFamilyFor(name) {
  return generatedSecretFamilies.find((family) => name === family || name.startsWith(`${family}_`));
}

function credentialAllowed(name, runtime, durable) {
  if (!Object.hasOwn(providerCredentialInventory, name)) return true;
  const holding = providerCredentialInventory[name][runtime];
  if (runtime === "worker") return holding === "yes";
  return holding === "yes" || (holding === "durable_false_only" && !durable);
}

function familyAllowed(family, runtime) {
  return secretFamilyInventory[family][runtime] === "yes";
}

function configuredValue(source, defaults, name) {
  if (Object.hasOwn(source, name)) return source[name];
  if (Object.hasOwn(defaults, name)) return defaults[name];
  return "";
}

/**
 * Encodes one dotenv value and proves the encoding round-trips through Node's parser. Trying the
 * unquoted form first keeps credentials readable as assignments; quoting handles spaces, `#`, JSON
 * and multiline values without ever printing them.
 */
export function serializeEnvValue(value, variable = "variable") {
  if (value.includes("\0")) {
    throw new EnvironmentDistributionError(`${variable} cannot contain a NUL byte`);
  }
  const candidates = [value];
  if (!value.includes("'")) candidates.push(`'${value}'`);
  if (!value.includes('"')) candidates.push(`"${value}"`);
  for (const candidate of candidates) {
    try {
      if (parseEnv(`VALUE=${candidate}`).VALUE === value) return candidate;
    } catch {
      // Try the next representation. No parser error is allowed to echo the candidate.
    }
  }
  throw new EnvironmentDistributionError(
    `${variable} cannot be represented safely in a Node dotenv file`,
  );
}

function renderEnvironment(runtime, names, values) {
  const lines = [
    "# Generated by pnpm env:distribute. Do not edit or commit this file.",
    `# ${runtime} runtime only; placement is enforced by architecture section 4.5.`,
    "",
  ];
  for (const name of names) {
    lines.push(`${name}=${serializeEnvValue(values[name] ?? "", name)}`);
  }
  return `${lines.join("\n")}\n`;
}

function familyVariableNames(source, defaults, runtime) {
  const names = [];
  for (const family of generatedSecretFamilies) {
    if (!familyAllowed(family, runtime)) continue;
    const candidates = new Set(
      [...Object.keys(defaults), ...Object.keys(source)].filter(
        (name) => name === family || name.startsWith(`${family}_`),
      ),
    );
    const versions = [...candidates]
      .filter((name) => /^[1-9][0-9]{0,8}$/.test(name.slice(family.length + 1)))
      .sort((a, b) => Number(a.slice(family.length + 1)) - Number(b.slice(family.length + 1)));
    names.push(...versions);
    const current = `${family}_CURRENT`;
    if (candidates.has(current)) names.push(current);
    if (candidates.has(family)) names.push(family);
    names.push(
      ...[...candidates]
        .filter(
          (name) =>
            name !== family &&
            name !== current &&
            !versions.includes(name) &&
            name.startsWith(`${family}_`),
        )
        .sort(),
    );
  }
  return names;
}

function serverPlan(runtime, source, exampleText) {
  const defaults = parseEnvSafe(exampleText, `${runtime} environment template`);
  const durable = (source.DURABLE ?? defaults.DURABLE) === "true";
  const fixedNames = assignmentNames(exampleText, `${runtime} environment template`).filter(
    (name) => {
      if (generatedFamilyFor(name)) return false;
      return credentialAllowed(name, runtime, durable);
    },
  );
  const familyNames = familyVariableNames(source, defaults, runtime);
  const names = [...fixedNames, ...familyNames];
  const values = Object.fromEntries(
    names.map((name) => [name, configuredValue(source, defaults, name)]),
  );
  return Object.freeze({ names: Object.freeze(names), values: Object.freeze(values) });
}

function webPlan(source, exampleText) {
  const defaults = parseEnvSafe(exampleText, "web environment template");
  const names = assignmentNames(exampleText, "web environment template");
  const values = Object.fromEntries(
    names.map((name) => [name, configuredValue(source, defaults, name)]),
  );
  return Object.freeze({ names: Object.freeze(names), values: Object.freeze(values) });
}

/** Builds all three target files in memory. No secret-bearing file is changed here. */
export function planEnvironmentDistribution(sourceText, exampleTexts) {
  const source = parseEnvSafe(sourceText, "source environment file");
  const api = serverPlan("api", source, exampleTexts.api);
  const worker = serverPlan("worker", source, exampleTexts.worker);
  const web = webPlan(source, exampleTexts.web);
  const used = new Set([...api.names, ...worker.names, ...web.names]);
  const sourceOnly = Object.keys(source).filter((name) => !used.has(name));
  const unowned = sourceOnly.filter((name) => !permittedSourceOnlyVariables.has(name));
  if (unowned.length > 0) {
    throw new EnvironmentDistributionError(
      `Source environment contains unowned assignments:\n${unowned
        .sort()
        .map((name) => `- ${name}`)
        .join("\n")}`,
    );
  }
  return Object.freeze({
    api: Object.freeze({ ...api, text: renderEnvironment("api", api.names, api.values) }),
    worker: Object.freeze({
      ...worker,
      text: renderEnvironment("worker", worker.names, worker.values),
    }),
    web: Object.freeze({ ...web, text: renderEnvironment("web", web.names, web.values) }),
    sourceOnlyCount: sourceOnly.length,
  });
}

function placementIssues(runtime, variables) {
  const issues = [];
  const durable = variables.DURABLE === "true";
  const fixedNames = new Set(runtime === "api" ? apiVariableNames : workerVariableNames);
  const familyNames = runtime === "api" ? apiSecretFamilies : workerSecretFamilies;
  for (const name of Object.keys(variables)) {
    const family = generatedFamilyFor(name);
    if (!fixedNames.has(name) && !(family && familyNames.includes(family))) {
      issues.push(`${name}: is not read by the ${runtime} runtime`);
      continue;
    }
    if (family && !familyAllowed(family, runtime)) {
      issues.push(`${name}: must not be assigned to the ${runtime}`);
      continue;
    }
    if (!credentialAllowed(name, runtime, durable)) {
      issues.push(`${name}: must not be assigned to the ${runtime}`);
    }
    if (runtime === "worker" && name === "TRIGGER_SECRET_KEY") {
      issues.push("TRIGGER_SECRET_KEY: Trigger.dev injects it; the worker file must not assign it");
    }
  }
  return issues;
}

function resultIssues(runtime, result) {
  if (result.ok) return [];
  return result.issues.map((issue) => `${runtime}.${issue.variable}: ${issue.message}`);
}

function familyEntries(variables, family) {
  return Object.entries(variables)
    .filter(([name]) => name.startsWith(`${family}_`))
    .sort(([a], [b]) => a.localeCompare(b));
}

function sharedFamilyIssues(api, worker) {
  const issues = [];
  for (const family of generatedSecretFamilies.filter(
    (candidate) => secretFamilyInventory[candidate].worker === "yes",
  )) {
    const apiEntries = familyEntries(api, family);
    const workerEntries = familyEntries(worker, family);
    const apiNames = apiEntries.map(([name]) => name);
    const workerNames = workerEntries.map(([name]) => name);
    if (apiNames.join("\0") !== workerNames.join("\0")) {
      issues.push(`${family}: api and worker must carry the same versions`);
      continue;
    }
    for (let index = 0; index < apiEntries.length; index += 1) {
      if (apiEntries[index][1] !== workerEntries[index][1]) {
        issues.push(`${apiEntries[index][0]}: api and worker values must match`);
      }
    }
  }
  return issues;
}

/** Validates placement, runtime schemas and shared-family equality without exposing a value. */
export function validateDistributedVariables({ api, worker, web }) {
  const publicNames = new Set(webVariableNames);
  const issues = [
    ...placementIssues("api", api),
    ...placementIssues("worker", worker),
    ...Object.keys(web)
      .filter((name) => !publicNames.has(name) || isSecretVariable(name))
      .map((name) =>
        isSecretVariable(name)
          ? `${name}: server secrets must never be assigned to the web app`
          : `${name}: is not read by the web runtime`,
      ),
    ...resultIssues("api", parseApiConfig(api)),
    ...resultIssues(
      "worker",
      parseWorkerConfig(worker, {
        platformInjected: false,
      }),
    ),
    ...resultIssues("web", parseWebConfig(web)),
    ...sharedFamilyIssues(api, worker),
  ];
  if (issues.length > 0) {
    throw new EnvironmentDistributionError(
      `Environment distribution is invalid:\n${[...new Set(issues)]
        .sort()
        .map((issue) => `- ${issue}`)
        .join("\n")}`,
    );
  }
}

function variablesFromPlan(plan) {
  return {
    api: parseEnvSafe(plan.api.text, "generated api environment"),
    worker: parseEnvSafe(plan.worker.text, "generated worker environment"),
    web: parseEnvSafe(plan.web.text, "generated web environment"),
  };
}

async function assertPrivateRegularFile(path, label) {
  let details;
  try {
    details = await stat(path);
  } catch {
    throw new EnvironmentDistributionError(`${label} is missing or unreadable: ${path}`);
  }
  if (!details.isFile()) {
    throw new EnvironmentDistributionError(`${label} is not a regular file: ${path}`);
  }
  if (process.platform !== "win32" && (details.mode & 0o077) !== 0) {
    throw new EnvironmentDistributionError(`${label} must have mode 600: ${path}`);
  }
}

async function atomicWritePrivate(path, text) {
  await mkdir(dirname(path), { recursive: true });
  const temporary = join(dirname(path), `.env.${process.pid}.${randomUUID()}.tmp`);
  try {
    await writeFile(temporary, text, { encoding: "utf8", flag: "wx", mode: privateMode });
    await chmod(temporary, privateMode);
    await rename(temporary, path);
    await chmod(path, privateMode);
  } catch (error) {
    await unlink(temporary).catch(() => undefined);
    throw error;
  }
}

async function readExamples(repoRoot) {
  return Object.fromEntries(
    await Promise.all(
      Object.entries(appTargets).map(async ([runtime, target]) => [
        runtime,
        await readFile(join(repoRoot, target.example), "utf8"),
      ]),
    ),
  );
}

/** Splits, validates and atomically writes the three ignored application environment files. */
export async function distributeEnvironment({
  repoRoot,
  sourcePath = join(repoRoot, ".env.local"),
}) {
  await assertPrivateRegularFile(sourcePath, "source environment file");
  const [sourceText, exampleTexts] = await Promise.all([
    readFile(sourcePath, "utf8"),
    readExamples(repoRoot),
  ]);
  const plan = planEnvironmentDistribution(sourceText, exampleTexts);
  validateDistributedVariables(variablesFromPlan(plan));
  await Promise.all(
    Object.entries(appTargets).map(([runtime, target]) =>
      atomicWritePrivate(join(repoRoot, target.output), plan[runtime].text),
    ),
  );
  return Object.freeze({
    assignments: Object.freeze({
      api: plan.api.names.length,
      worker: plan.worker.names.length,
      web: plan.web.names.length,
    }),
    sourceOnlyCount: plan.sourceOnlyCount,
  });
}

/** Re-validates already-distributed files, including their private filesystem modes. */
export async function checkDistributedEnvironment({ repoRoot }) {
  const entries = await Promise.all(
    Object.entries(appTargets).map(async ([runtime, target]) => {
      const path = join(repoRoot, target.output);
      await assertPrivateRegularFile(path, `${runtime} environment file`);
      const text = await readFile(path, "utf8");
      return [runtime, parseEnvSafe(text, `${runtime} environment file`)];
    }),
  );
  const variables = Object.fromEntries(entries);
  validateDistributedVariables(variables);
  return Object.freeze({
    assignments: Object.freeze(
      Object.fromEntries(entries.map(([runtime, env]) => [runtime, Object.keys(env).length])),
    ),
  });
}
