import { z } from "zod";
import { isStableCode, stableCodeSchema } from "./primitives.ts";

/** The maximum length of an error message; messages are safe, fixed texts. */
export const errorMessageMaxLength = 500;

/** Request ids are opaque tokens generated by the api and echoed in logs and envelopes. */
export const requestIdSchema = z
  .string({ error: "Expected a request id" })
  .regex(/^[A-Za-z0-9._:-]{1,128}$/, { error: "Expected a request id" });

/** An error or notice code carried by an envelope or a WebSocket `err` frame. */
export const errorCodeSchema = stableCodeSchema;

/** The body of an API error response (§6). `details` never contains secrets or user content. */
export interface ErrorBody<Code extends string = string> {
  code: Code;
  message: string;
  details?: Record<string, unknown>;
  requestId: string;
}

/** Every API error is returned as `{ "error": { code, message, details?, requestId } }`. */
export interface ErrorEnvelope<Code extends string = string> {
  error: ErrorBody<Code>;
}

const errorMessageSchema = z
  .string({ error: "Expected an error message" })
  .min(1, { error: "Expected an error message" })
  .max(errorMessageMaxLength, { error: "Error message is too long" });

/** Any error envelope. Unknown keys are rejected at both levels. */
export const errorEnvelopeSchema = z.strictObject({
  error: z.strictObject({
    code: errorCodeSchema,
    message: errorMessageSchema,
    details: z.record(z.string(), z.unknown()).optional(),
    requestId: requestIdSchema,
  }),
});

/** The envelope schema for one code without details: `details` must be absent. */
export function errorEnvelopeSchemaFor<const Code extends string>(code: Code) {
  assertStableCode(code);
  return z.strictObject({
    error: z.strictObject({
      code: z.literal(code),
      message: errorMessageSchema,
      requestId: requestIdSchema,
    }),
  });
}

/** The envelope schema for one code whose `details` are required and validated. */
export function errorEnvelopeWithDetailsSchemaFor<
  const Code extends string,
  Details extends z.ZodType<Record<string, unknown>>,
>(code: Code, details: Details) {
  assertStableCode(code);
  return z.strictObject({
    error: z.strictObject({
      code: z.literal(code),
      message: errorMessageSchema,
      details,
      requestId: requestIdSchema,
    }),
  });
}

function assertStableCode(code: string): void {
  if (!isStableCode(code)) {
    throw new Error(`Invalid error code "${code}": use lowercase dotted identifiers`);
  }
}

/** The `Retry-After` value in whole seconds: at most one day. */
export const retryAfterSecondsSchema = z
  .number({ error: "Expected retryAfter in whole seconds" })
  .int({ error: "Expected retryAfter in whole seconds" })
  .min(1, { error: "Expected retryAfter in whole seconds" })
  .max(86_400, { error: "Expected retryAfter in whole seconds" });

/** `rate.limited` details; the same value is sent as the `Retry-After` header. */
export const rateLimitedErrorDetailsSchema = z.strictObject({
  retryAfter: retryAfterSecondsSchema,
});
export type RateLimitedErrorDetails = z.infer<typeof rateLimitedErrorDetailsSchema>;

/** The complete `rate.limited` envelope. */
export const rateLimitedErrorSchema = errorEnvelopeWithDetailsSchemaFor(
  "rate.limited",
  rateLimitedErrorDetailsSchema,
);

/**
 * One validation failure: where it happened and a fixed message. Messages never echo the submitted
 * value, so validation errors cannot leak passphrases, Vault values or document text.
 */
export const validationIssueSchema = z.strictObject({
  path: z.array(z.union([z.string().max(200), z.number().int().nonnegative()])).max(32),
  code: z.string().regex(/^[a-z_]{1,64}$/),
  message: z.string().min(1).max(300),
});
export type ValidationIssue = z.infer<typeof validationIssueSchema>;

/** `validation` details: at most 100 issues. */
export const validationErrorDetailsSchema = z.strictObject({
  issues: z.array(validationIssueSchema).min(1).max(100),
});
export type ValidationErrorDetails = z.infer<typeof validationErrorDetailsSchema>;

/** The complete `validation` envelope. */
export const validationErrorSchema = errorEnvelopeWithDetailsSchemaFor(
  "validation",
  validationErrorDetailsSchema,
);
