import { z } from "./zod.ts";

/**
 * Required on every mutation with side effects (§6.1). Header names are case-insensitive; Node
 * lowercases incoming names, so servers read `idempotencyKeyHeader.toLowerCase()`.
 */
export const idempotencyKeyHeader = "Idempotency-Key";

/**
 * The `Idempotency-Key` header value: 16 to 128 URL-safe characters, for example a UUID generated by
 * the client per logical mutation. Keys are stored in `idempotency_records` and never carry data.
 */
export const idempotencyKeySchema = z
  .string({ error: "Expected an Idempotency-Key" })
  .regex(/^[A-Za-z0-9_-]{16,128}$/, {
    error: "Expected an Idempotency-Key of 16 to 128 URL-safe characters",
  });

export type IdempotencyKey = z.infer<typeof idempotencyKeySchema>;

/**
 * The notice returned when an exact retry reaches an endpoint that mints a one-time secret (§6.1,
 * decision R11). The response is 200 without the secret, and the UI offers Revoke and replace.
 */
export const secretAlreadyIssuedNotice = "secret.already_issued";

const reservedOneTimeSecretKeys = new Set(["secretUnavailable", "notice"]);

/**
 * The response of an endpoint that mints a one-time secret (invite codes, API keys, share tokens,
 * OAuth codes; §6.1). The first response carries the non-secret fields, the secret fields and
 * `secretUnavailable: false`. An exact retry replays only the redacted outcome: the non-secret
 * fields with `secretUnavailable: true` and `notice: "secret.already_issued"`. Both variants are
 * strict, so a replay can never carry a secret field.
 *
 * Throws when a key is declared in both shapes or uses a reserved name.
 */
export function oneTimeSecretResponseSchema<
  const Fields extends z.ZodRawShape,
  const Secret extends z.ZodRawShape,
>(fields: Fields, secret: Secret) {
  for (const key of Object.keys(fields)) {
    if (reservedOneTimeSecretKeys.has(key)) {
      throw new Error(`"${key}" is reserved in one-time secret responses`);
    }
  }
  const secretKeys = Object.keys(secret);
  if (secretKeys.length === 0) {
    throw new Error("A one-time secret response needs at least one secret field");
  }
  for (const key of secretKeys) {
    if (reservedOneTimeSecretKeys.has(key)) {
      throw new Error(`"${key}" is reserved in one-time secret responses`);
    }
    if (Object.hasOwn(fields, key)) {
      throw new Error(`"${key}" cannot be both a secret and a non-secret field`);
    }
  }
  return z.discriminatedUnion("secretUnavailable", [
    z.strictObject({ ...fields, ...secret, secretUnavailable: z.literal(false) }),
    z.strictObject({
      ...fields,
      secretUnavailable: z.literal(true),
      notice: z.literal(secretAlreadyIssuedNotice),
    }),
  ]);
}
